# This file was generated by the {rix} R package v0.16.0 on 2025-08-14
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = c("DBI",
#  > "KernSmooth",
#  > "MASS",
#  > "R6",
#  > "RColorBrewer",
#  > "Rcpp",
#  > "RcppArmadillo",
#  > "XML",
#  > "abind",
#  > "askpass",
#  > "base64enc",
#  > "bit",
#  > "bit64",
#  > "bslib",
#  > "cachem",
#  > "callr",
#  > "class",
#  > "classInt",
#  > "cli",
#  > "colorspace",
#  > "cols4all",
#  > "coro",
#  > "cpp11",
#  > "crayon",
#  > "crosstalk",
#  > "curl",
#  > "data.table",
#  > "desc",
#  > "digest",
#  > "dplyr",
#  > "e1071",
#  > "evaluate",
#  > "farver",
#  > "fastmap",
#  > "fontawesome",
#  > "fs",
#  > "generics",
#  > "geojsonsf",
#  > "geometries",
#  > "glue",
#  > "highr",
#  > "hms",
#  > "htmltools",
#  > "htmlwidgets",
#  > "httpuv",
#  > "httr",
#  >  "httr2",
#  > "jpeg",
#  > "jquerylib",
#  > "jsonify",
#  > "jsonlite",
#  > "knitr",
#  > "labeling",
#  > "later",
#  > "lattice",
#  > "lazyeval",
#  > "leafem",
#  > "leafgl",
#  > "leaflegend",
#  > "leaflet",
#  > "leaflet.providers",
#  > "leafsync",
#  > "lifecycle",
#  > "logger",
#  > "lubridate",
#  > "luz",
#  > "lwgeom",
#  > "magrittr",
#  > "maptiles",
#  > "memoise",
#  > "mime",
#  > "ntfy",
#  > "openssl",
#  > "pillar",
#  > "pkgconfig",
#  > "png",
#  > "prettyunits",
#  > "processx",
#  > "progress",
#  > "promises",
#  > "proxy",
#  > "ps",
#  > "purrr",
#  > "randomForest",
#  > "rapidjsonr",
#  > "rappdirs",
#  > "raster",
#  > "renv",
#  > "rlang",
#  > "rmarkdown",
#  > "rstac",
#  > "s2",
#  >  "safetensors",
#  > "sass",
#  > "scales",
#  > "servr",
#  > "sf",
#  > "sfheaders",
#  > "slider",
#  > "slippymath",
#  > "sp",
#  > "spacesXYZ",
#  > "stars",
#  > "stringdist",
#  > "stringi",
#  > "stringr",
#  > "sys",
#  > "terra",
#  > "tibble",
#  > "tidyr",
#  > "tidyselect",
#  > "timechange",
#  > "tinytex",
#  > "tmap",
#  > "tmaptools",
#  > "torch",
#  > "units",
#  > "utf8",
#  > "vctrs",
#  > "viridisLite",
#  > "warp",
#  > "withr",
#  > "wk",
#  > "xfun",
#  > "yaml",
#  > "zeallot"),
#  > git_pkgs = list(sits = list(package_name = "sits",
#  > repo_url = "https://github.com/e-sensing/sits",
#  > commit = "b20e3cb84232672e5fadf4607eab488ec2e5fe53")),
#  > project_path = "~/Downloads/")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-08-11.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      abind
      askpass
      base64enc
      bit
      bit64
      bslib
      cachem
      callr
      class
      classInt
      cli
      colorspace
      cols4all
      coro
      cpp11
      crayon
      crosstalk
      curl
      data_table
      DBI
      desc
      digest
      dplyr
      e1071
      evaluate
      farver
      fastmap
      fontawesome
      fs
      generics
      geojsonsf
      geometries
      glue
      highr
      hms
      htmltools
      htmlwidgets
      httpuv
      httr
      httr2
      jpeg
      jquerylib
      jsonify
      jsonlite
      KernSmooth
      knitr
      labeling
      later
      lattice
      lazyeval
      leafem
      leafgl
      leaflegend
      leaflet
      leaflet_providers
      leafsync
      lifecycle
      logger
      lubridate
      luz
      lwgeom
      magrittr
      maptiles
      MASS
      memoise
      mime
      ntfy
      openssl
      pillar
      pkgconfig
      png
      prettyunits
      processx
      progress
      promises
      proxy
      ps
      purrr
      R6
      randomForest
      rapidjsonr
      rappdirs
      raster
      RColorBrewer
      Rcpp
      RcppArmadillo
      renv
      rlang
      rmarkdown
      rstac
      s2
      safetensors
      sass
      scales
      servr
      sf
      sfheaders
      slider
      slippymath
      sp
      spacesXYZ
      stars
      stringdist
      stringi
      stringr
      sys
      terra
      tibble
      tidyr
      tidyselect
      timechange
      tinytex
      tmap
      tmaptools
      torch
      units
      utf8
      vctrs
      viridisLite
      warp
      withr
      wk
      xfun
      XML
      yaml
      zeallot;
  };
 
    sits = (pkgs.rPackages.buildRPackage {
      name = "sits";
      src = pkgs.fetchgit {
        url = "https://github.com/e-sensing/sits";
        rev = "b20e3cb84232672e5fadf4607eab488ec2e5fe53";
        sha256 = "sha256-a3PvpyIT9CKMLL6KAmt9CV37rYKYhT94uSyrA6fmhrI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          yaml
          dplyr
          leafgl
          leaflet
          lubridate
          luz
          purrr
          randomForest
          Rcpp
          rstac
          sf
          slider
          terra
          tibble
          tidyr
          tmap
          torch
          units
          RcppArmadillo;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ sits rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
