// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_trajectory_transition_analysis
NumericMatrix C_trajectory_transition_analysis(NumericMatrix data, int reference_class, int neighbor_class);
RcppExport SEXP _restoremasks_C_trajectory_transition_analysis(SEXP dataSEXP, SEXP reference_classSEXP, SEXP neighbor_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< int >::type neighbor_class(neighbor_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_transition_analysis(data, reference_class, neighbor_class));
    return rcpp_result_gen;
END_RCPP
}
// C_trajectory_neighbor_analysis
NumericMatrix C_trajectory_neighbor_analysis(NumericMatrix data, int reference_class, int replacement_class);
RcppExport SEXP _restoremasks_C_trajectory_neighbor_analysis(SEXP dataSEXP, SEXP reference_classSEXP, SEXP replacement_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type reference_class(reference_classSEXP);
    Rcpp::traits::input_parameter< int >::type replacement_class(replacement_classSEXP);
    rcpp_result_gen = Rcpp::wrap(C_trajectory_neighbor_analysis(data, reference_class, replacement_class));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_restoremasks_C_trajectory_transition_analysis", (DL_FUNC) &_restoremasks_C_trajectory_transition_analysis, 3},
    {"_restoremasks_C_trajectory_neighbor_analysis", (DL_FUNC) &_restoremasks_C_trajectory_neighbor_analysis, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_restoremasks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
