# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_trajectory_transition_analysis <- function(data, reference_class, neighbor_class) {
    .Call(`_restoremasks_C_trajectory_transition_analysis`, data, reference_class, neighbor_class)
}

